version: '3.8'
services:
  postgres:
    container_name: mhh-postgres
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: myhomehunt
    ports:
      - "5001:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
  myhomehunt:
    build:
      context: ./NextMyHomeHunt
      dockerfile: Dockerfile
    container_name: mhh-container
    ports:
      - "3000:3000"
    volumes:
      - ./NextMyHomeHunt/:/app
    depends_on:
      postgres:
        condition: service_healthy
    command: yarn dev

volumes:
  pgdata:
