version: '3.8'
services:
  postgres:
    container_name: mhh-postgres
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: myhomehunt
    ports:
      - "5001:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  graphql:
    build:
      context: ./GraphQL/MyHomeHunt
      dockerfile: Dockerfile
    container_name: mhh-graphql-api
    ports:
      - "5000:5000"
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - ./GraphQL/MyHomeHunt/.env

  api:
    build:
      context: ./API
      dockerfile: Dockerfile
    container_name: mhh-api
    restart: always
    ports:
      - "4443:4443"
    volumes:
      - ./API:/app
    env_file:
      - ./API/.env

  myhomehunt:
    build:
      context: ./MyHomeHunt
      dockerfile: Dockerfile
    container_name: mhh-container
    ports:
      - "3000:3000"
    volumes:
      - ./MyHomeHunt/:/app
    depends_on:
      postgres:
        condition: service_healthy
    command: yarn dev

volumes:
  pgdata:
