version: '3.8'
services:
  postgres:
    container_name: mhh-postgres
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: myhomehunt
    ports:
      - "5001:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  postgraphile:
    container_name: mhh-postgraphile-api
    image: graphile/postgraphile:4
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/myhomehunt
      GRAPHQL_SCHEMA: public
    depends_on:
      postgres:
        condition: service_healthy

  graphql:
    build:
      context: ./GraphQL/MyHomeHunt
      dockerfile: Dockerfile
    container_name: mhh-graphql-api
    ports:
      - "4443:4443"
    environment:
      POSTGRES_SCHEMA: public
      POSTGRES_DB: myhomehunt
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      DB_HOST: postgres
      LISTEN_PORT: 5000
      GRAPHQL_LISTEN_PORT: 4443
    depends_on:
      postgres:
        condition: service_healthy

  ui:
    build:
      context: ./UI
      dockerfile: Dockerfile
    container_name: mhh-container
    ports:
      - "3000:3000"
    volumes:
      - ./UI/:/app
    depends_on:
      postgres:
        condition: service_healthy
    command: yarn dev

volumes:
  pgdata:
